version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: my_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "4500:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
